### ISSUE TITLE
Devices are not found as new device in Sunny Portal

### ISSUE THREAD

**Issue by tho-wa** [camueller/SmartApplianceEnabler#1]
Issue is discussed here:
http://www.photovoltaikforum.com/sma-anlagenueberwachung-f48/geraete-mit-home-manager-koppeln-via-semp-ethernet-t104060-s120.html (german only)

**Comment by camueller** [comment]
The attributes of PowerInfo were merged into PowerConsumption. This has been fixed by the following commits:
- https://github.com/camueller/SmartApplianceEnabler/commit/29ad96e0fa18a36eeaef384a3f437e8a45d8e5cb
- https://github.com/camueller/SmartApplianceEnabler/commit/d1afc393138c6d600bfe622f7a4aa786b4438e9e
