### ISSUE TITLE
Three phase loads?

### ISSUE THREAD

**Issue by titoflebof** [camueller/SmartApplianceEnabler#30]
Thanks for this great development.
Is there anything planned to support 3 phase loads?
As such a load is normally symetrical, the idea could be to out One sonoff pow driving a contactor and measuring power on one phase. SAE should only triple the power measured. But I dont have Seen anything like this in the SEMP spec.
Regards Titof

**Comment by camueller** [comment]
Originally I wanted to support 3 phase devices in a way where each phase is switched by a solid state relay. I dropped that idea since it makes much more sense to use contactors controlled by single solid state relay. And for measuring 3 phase devices I used ordinary meters like http://bg-etech.de/bgshop/product_info.php/drehstromzaehler-drt428-p-441 .
